trigger:
  branches:
    include:
      - main  # Adjust based on your default branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    echo "Building the HTML file..."
    mkdir output
    cp index.html output/
  displayName: 'Copy HTML File'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'output'
    ArtifactName: 'html-files'
    publishLocation: 'Container'
